### ISSUE TITLE
Supplement input box with backdrop-filter

### ISSUE THREAD

**Issue by themrburns** [Rot547/BF-Map-Guesser#4]
Use a transparent background and blur it for readability;

`background: none;
backdrop-filter: blur(1rem);`

**Comment by themrburns** [comment]
Also, to improve the readability of the placeholder text:

```css
#guess::placeholder {
  color: black;
}
```
